name: test-node-script

on:
  workflow_dispatch:
  push:
    branches: [
      test_action
    ]

jobs:
  ubuntu:
    name: Ubuntu 18.04
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup ZeroTier
        uses: ./
        with:
          network_id: ${{ secrets.ZT_NETWORK_ID }}

  windows:
    name: Windows
    runs-on: windows-2019

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup ZeroTier
        uses: ./
        with:
          network_id: ${{ secrets.ZT_NETWORK_ID }}
